name: Cloud Run Deploy

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: net-poc-projects
  REGION: southamerica-east1
  SERVICE_NAME: host-api
  IMAGE_NAME: host-api
  REPO_NAME: host-api-repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      # 1. Setup .NET SDK (2026 uses .NET 10)
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      # 2. Run Unit Tests
      # Using --logger:github allows to see test failures directly in the PR/Action UI
      - name: Run Tests
        working-directory: ./Host/Api.Test
        run: |
          dotnet restore
          dotnet test --no-restore --verbosity normal --logger:"GitHubActions;summary=true"
        
      # 3. Login to GCP using JSON Key
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # 4. Configure Docker for Artifact Registry
      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      # 5. Build & Push Image
      - name: Build and Push
        run: |
          TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          echo "current workspace: ${{ github.workspace }}"
          docker build -t $TAG -f ./Host/Api/Dockerfile .
          docker push $TAG
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      # 6. Deploy to Cloud Run
      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.IMAGE_TAG }}
          flags: '--allow-unauthenticated'
          secrets: ConnectionStrings__DefaultConnection=DB_CONNECTION_STRING_MONGODB:latest
